version: '3.7'

services:
  react:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: react-front
    ports:
      - 3004:3000
    restart: always
    tty: true
    volumes:
      - ./:/home/react-front
    
  
    

